version: '3.8'
services:
  app:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    image: 'api-commerce/laravel'
    container_name: app
    tty: true
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
        - app-network
  
  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/conf:/etc/nginx/conf.d
    networks:
      - app-network
  
  db:
    image: postgres:12
    container_name: db
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devsecret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
